#ifndef USER_CONFIG
#define USER_CONFIG

#define MY_SSID "NAME OF YOUR NETWORK"
#define PASSWORD "PASSWORD OF YOUR NETWORK"
#define MQTT_SERVER "192....."
#define MQTT_PORT 1883
#define MQTT_USER ""
#define MQTT_PASSWORD ""

#endif